language: objective-c  #1
osx_image: xcode7.2 #2
xcode_project: WormholeKitFramework.xcodeproj #3
xcode_scheme: WormholeKitFramework #4
xcode_sdk: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk #5
script: xctool -project WormholeKitFramework.xcodeproj -scheme  WormholeKitFramework build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
